services:
  postgres:
    image: postgres:15-alpine
    container_name: wallet_postgres
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_EXTERNAL_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    networks:
      - wallet-network

  app:
    build: .
    container_name: wallet_app
    env_file: .env
    environment:
      DB_HOST: postgres
      DOCKER_CONTAINER: "true"
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - wallet-network

networks:
  wallet-network:
    driver: bridge

volumes:
  postgres_data: